### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by slavi010** [hugshoney/barnacle-bot#1]
Hi,

Can you add a requirements.txt for all dependencies ?

Auto-create the file:
```python
pip freeze > requirements.txt
```

Install with one cmd all dependencies from the file:
```python
pip install -r requirements.txt
```

Thanks 👍

**Comment by hugshoney** [comment]
Done. I add `requirements.txt` in my repository.
I don't have much experience of using `venv`, and I'm not use many external dependencies.
So, I don't add those file previously, because I think no one will read or try my code :smile_cat:.

**Comment by slavi010** [comment]
He he, we are in the same situation for python/English.
Remind to close this issue !
