### ISSUE TITLE
Improuve the README.md (token ?)

### ISSUE THREAD

**Issue by slavi010** [hugshoney/barnacle-bot#2]
I need a token ```telegram.error.InvalidToken: Invalid token```.
But for what is it ?
Where i can get one ?

You can add a "instructions" section for your readme.

**Comment by slavi010** [comment]
Ho, and the same time, add your python version.

**Comment by hugshoney** [comment]
First, you need to create Telegram Bot via [BotFather](https://t.me/botfather). You will receive token for your own Telegram bot like this `110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw`. Copy and past in `config.ini` file.

For more information you can read [this introduction](https://core.telegram.org/bots#6-botfather) from Telegram.

**Comment by hugshoney** [comment]
I use Python 3.
I will try to add little instruction in README.md

**Comment by slavi010** [comment]
Nice, thanks !

**Comment by slavi010** [comment]
I guess you need an Telegram account ?

**Comment by hugshoney** [comment]
Sure, you need Telegram account. How you can interact with Telegram bot without having any Telegram account.

**Comment by slavi010** [comment]
Magic ?

**Comment by hugshoney** [comment]
There is no magic in here. You need Telegram accout :smile_cat:.
Are you never use Telegram before?

**Comment by slavi010** [comment]
No, I generally use [Signal](signal.org).
So its going to be the first time i use it ^^

**Comment by hugshoney** [comment]
If you never use Telegram. Maybe you can try another project, like making bot for Discord, Slack, Reddit, WhatsApp (fyi, I never tried making all of this).
The codes that I write in `plugins` folder can be use without using `main.py`, because I write those stuff as Python module.

**Comment by hugshoney** [comment]
I never use Signal but probably you can try to make Signal bot.

[Signal API Protocol](https://github.com/signalapp/Signal-Server/wiki/API-Protocol)

**Comment by slavi010** [comment]
I tested the programme but i got this issue : ```caused error "'NoneType' object has no attribute 'reply_text'"```

**Comment by slavi010** [comment]
When i test ```/slang test```. Same error for mean and synonym

**Comment by hugshoney** [comment]
Thats not happen to me :confused:.

**Comment by slavi010** [comment]
Ho, it seems to work now. I don't know why but occasionally there is an error that occurs :/

**Comment by slavi010** [comment]
![image](https://user-images.githubusercontent.com/49365528/83474510-34ea3e80-a45a-11ea-9a29-438a10983f2b.png)

**Comment by hugshoney** [comment]
I use all free public API to get any list of definition, synonym, slang, and quotes. Maybe this thing that make some error, because there is limit when making request to API url.

**Comment by hugshoney** [comment]
[add Quick Start Guide](https://github.com/hugshoney/barnacle-bot/commit/baa24124437d916dccc609c1f387509ed948cc20) to README.
